#
#   DashAR - An AR-based HUD for Automobiles.
#   (c)2024-2026 Trevor D. Brown. Distributed under the MIT license.
#
#   File:       das_service.pyi
#

import argparse
import asyncio
import tornado
from das_core.configuration import Configuration

class DashARWelcomeHandler(tornado.web.RequestHandler):
    def initialize(self) -> None: ...
    def get(self) -> None: ...

class DashARStatusHandler(tornado.web.RequestHandler):
    dashar_configuration: Configuration
    def initialize(self, dashar_configuration: Configuration) -> None: ...
    def get(self) -> None: ...

class DashARHUDHandler(tornado.web.RequestHandler):
    dashar_configuration: Configuration
    def initialize(self, dashar_configuration: Configuration) -> None: ...
    def get(self) -> None: ...

class OBDIIHandler(tornado.web.RequestHandler):
    dashar_configuration: Configuration
    def initialize(self, dashar_configuration: Configuration) -> None: ...
    def get(self) -> None: ...

class TerminateHandler(tornado.web.RequestHandler):
    dashar_configuration: Configuration
    shutdown_event: asyncio.Event
    def initialize(
        self, shutdown_event: asyncio.Event, dashar_configuration: Configuration
    ) -> None: ...
    def get(self) -> None: ...

class UnimplementedHandler(tornado.web.RequestHandler):
    def initialize(self) -> None: ...
    def get(self) -> None: ...

class NotFoundHandler(tornado.web.RequestHandler):
    def initialize(self) -> None: ...
    def get(self) -> None: ...

class FailedInitHandler(tornado.web.RequestHandler):
    def initialize(self) -> None: ...
    def get(self) -> None: ...

def make_app(
    dashar_configuration: Configuration, shutdown_event: asyncio.Event
) -> tornado.web.Application: ...
def make_app_failed_init(
    dashar_configuration: Configuration, shutdown_event: asyncio.Event
) -> tornado.web.Application: ...
def check_for_arguments() -> argparse.Namespace: ...
async def main() -> None: ...
